### PR TITLE
Fixes issue compiling on Flutter beta 2.5.0-5.1.pre, due to method si…

### LINKED ISSUE #14: Incompatible with the latest Flutter beta (2.5.0-5.1.pre)
```
../../../../.pub-cache/hosted/pub.dartlang.org/assorted_layout_widgets-5.0.2/lib/src/text_one_line_ellipsis_with_fade.dart:995:20: Error: The method 'RenderParagraphX.getBoxesForSelection' has fewer named arguments than those of overridden method 'RenderParagraph.getBoxesForSelection'.
  List<ui.TextBox> getBoxesForSelection(TextSelection selection) {
```

### PR DESCRIPTION
**Pull request by josh-burton**
…gnature change

Fixes #14

### CODE REVIEW

**Review by kuhnroyal — APPROVED** [review]

**Comment by kuhnroyal** [comment]
Ran into this as well.

**Comment by hiperonii** [comment]
I found this issue too.

**Comment by MrCsabaToth** [comment]
Thanks for the work

**Comment by MrCsabaToth** [comment]
It's been a month since this PR and now 2.5 is stable. Please merge this and release a new version.

**Comment by niteshsrivats** [comment]
Running into the same issue as well. Any ETA on the new release with this fix?

**Comment by rutulspyveb** [comment]
Please merge waiting

**Comment by eldarkk** [comment]
Merge it please .......

**Review by marcglasberg — APPROVED** [review]

**Pull request merged**
